import argparse
import json
import sys
import time
from pathlib import Path

import cv2
import numpy as np


OUTPUT_DIR = Path("outputs/wall_coords")
FIXED_WALL_WIDTH_MM = 1030.0
FIXED_WALL_HEIGHT_MM = 1420.0
DEFAULT_REFERENCE_MARKER_IDS = [37, 25, 12, 8]
FIXED_REFERENCE_MARKER_WALL_CORNERS = {
    37: np.array(
        [
            [0.0, 50.0],
            [50.0, 50.0],
            [50.0, 0.0],
            [0.0, 0.0],
        ],
        dtype=np.float32,
    ),
    25: np.array(
        [
            [980.0, 50.0],
            [1030.0, 50.0],
            [1030.0, 0.0],
            [980.0, 0.0],
        ],
        dtype=np.float32,
    ),
    12: np.array(
        [
            [0.0, 1420.0],
            [50.0, 1420.0],
            [50.0, 1370.0],
            [0.0, 1370.0],
        ],
        dtype=np.float32,
    ),
    8: np.array(
        [
            [980.0, 1420.0],
            [1030.0, 1420.0],
            [1030.0, 1370.0],
            [980.0, 1370.0],
        ],
        dtype=np.float32,
    ),
}
FIXED_REFERENCE_MARKER_LAYOUTS = {
    37: "left_bottom",
    25: "right_bottom",
    12: "left_top",
    8: "right_top",
}


def parse_args():
    parser = argparse.ArgumentParser(
        description="Convert Aruco detection JSON into wall-plane coordinates."
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to detection JSON generated by aruco_detect.py",
    )
    parser.add_argument(
        "--marker-size-mm",
        type=float,
        required=True,
        help="Physical size of the reference Aruco marker in millimeters",
    )
    parser.add_argument(
        "--origin-marker-id",
        type=int,
        help="Marker ID used as wall coordinate origin. Default: first detected marker",
    )
    parser.add_argument(
        "--reference-marker-ids",
        nargs="+",
        type=int,
        help=(
            "Optional fixed reference marker IDs for whole-wall mapping. "
            f"Current supported layout: {' '.join(str(marker_id) for marker_id in DEFAULT_REFERENCE_MARKER_IDS)}"
        ),
    )
    parser.add_argument(
        "--origin",
        choices=["top_left", "center", "bottom_left"],
        default="top_left",
        help="Wall coordinate origin on the reference marker. Default: top_left",
    )
    args = parser.parse_args()
    if args.reference_marker_ids and len(args.reference_marker_ids) < 2:
        parser.error("--reference-marker-ids 至少需要 2 个 marker IDs。")
    return args


def ensure_output_dir(output_dir=OUTPUT_DIR):
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def validate_input_path(input_path):
    path = Path(input_path)
    if not path.exists():
        raise FileNotFoundError(f"输入 JSON 路径不存在: {path}")
    if not path.is_file():
        raise FileNotFoundError(f"输入路径不是文件: {path}")
    return path


def load_detection_json(input_path):
    try:
        payload = json.loads(input_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"JSON 解析失败: {exc}") from exc

    if "markers" not in payload:
        raise RuntimeError("输入 JSON 缺少 markers 字段")

    return payload


def get_reference_marker(markers, origin_marker_id):
    if not markers:
        raise RuntimeError("检测结果中没有 marker，无法生成墙面坐标")

    if origin_marker_id is None:
        return markers[0]

    for marker in markers:
        if marker.get("id") == origin_marker_id:
            return marker

    raise RuntimeError(f"未找到 origin marker id: {origin_marker_id}")


def normalize_reference_marker_ids(reference_marker_ids):
    if not reference_marker_ids:
        return None

    normalized = []
    seen = set()
    for marker_id in reference_marker_ids:
        marker_id = int(marker_id)
        if marker_id in seen:
            continue
        seen.add(marker_id)
        normalized.append(marker_id)

    if len(normalized) < 2:
        raise RuntimeError("固定参考模式至少需要 2 个 reference marker IDs")

    unsupported_ids = [
        marker_id
        for marker_id in normalized
        if marker_id not in FIXED_REFERENCE_MARKER_WALL_CORNERS
    ]
    if unsupported_ids:
        raise RuntimeError(
            "当前固定墙面参考几何只支持这些 reference marker IDs: "
            f"{sorted(FIXED_REFERENCE_MARKER_WALL_CORNERS.keys())}，"
            f"收到: {unsupported_ids}"
        )

    return normalized


def normalize_point(point, context="point"):
    if isinstance(point, dict):
        x_value = point.get("x")
        y_value = point.get("y")
    elif isinstance(point, (tuple, list, np.ndarray)) and len(point) >= 2:
        x_value, y_value = point[0], point[1]
    else:
        raise RuntimeError(f"{context} 坐标格式不支持: {point!r}")

    if x_value is None or y_value is None:
        raise RuntimeError(f"{context} 缺少 x/y 坐标: {point!r}")

    return float(x_value), float(y_value)


def get_reference_markers_by_ids(markers, reference_marker_ids, require_all=True):
    markers_by_id = {marker.get("id"): marker for marker in markers}
    found_markers = [
        markers_by_id[marker_id]
        for marker_id in reference_marker_ids
        if marker_id in markers_by_id
    ]
    missing_ids = [
        marker_id
        for marker_id in reference_marker_ids
        if marker_id not in markers_by_id
    ]

    if require_all and missing_ids:
        raise RuntimeError(
            "未找到全部 reference markers: "
            f"required={reference_marker_ids}, missing={missing_ids}"
        )

    return found_markers, missing_ids


def corners_to_array(marker):
    corners = marker.get("corners", [])
    if len(corners) != 4:
        raise RuntimeError(f"marker {marker.get('id')} 的 corners 数量不是 4")

    return np.array(
        [
            list(normalize_point(corner, f"marker {marker.get('id')} corner"))
            for corner in corners
        ],
        dtype=np.float32,
    )


def build_reference_wall_points(marker_size_mm, origin_mode):
    if marker_size_mm <= 0:
        raise ValueError("marker-size-mm 必须大于 0")

    if origin_mode == "center":
        half = marker_size_mm / 2.0
        return np.array(
            [
                [-half, -half],
                [half, -half],
                [half, half],
                [-half, half],
            ],
            dtype=np.float32,
        )

    if origin_mode == "bottom_left":
        return np.array(
            [
                [0.0, marker_size_mm],
                [marker_size_mm, marker_size_mm],
                [marker_size_mm, 0.0],
                [0.0, 0.0],
            ],
            dtype=np.float32,
        )

    # top_left (default)
    return np.array(
        [
            [0.0, 0.0],
            [marker_size_mm, 0.0],
            [marker_size_mm, marker_size_mm],
            [0.0, marker_size_mm],
        ],
        dtype=np.float32,
    )


def get_fixed_reference_wall_points(marker_id):
    try:
        return FIXED_REFERENCE_MARKER_WALL_CORNERS[int(marker_id)]
    except KeyError as exc:
        raise RuntimeError(f"不支持的固定 reference marker id: {marker_id}") from exc


def compute_homography(reference_marker, marker_size_mm, origin_mode):
    image_points = corners_to_array(reference_marker)
    wall_points = build_reference_wall_points(marker_size_mm, origin_mode)

    homography = cv2.getPerspectiveTransform(image_points, wall_points)
    if homography is None:
        raise RuntimeError("单应性矩阵计算失败")

    return homography


def compute_fixed_reference_homography(reference_markers, reference_marker_ids):
    image_points = []
    wall_points = []

    for marker_id, marker in zip(reference_marker_ids, reference_markers):
        image_points.extend(corners_to_array(marker).tolist())
        wall_points.extend(get_fixed_reference_wall_points(marker_id).tolist())

    image_points = np.array(image_points, dtype=np.float32)
    wall_points = np.array(wall_points, dtype=np.float32)

    homography, _ = cv2.findHomography(image_points, wall_points, method=0)
    if homography is None:
        raise RuntimeError("固定参考单应性矩阵计算失败")

    return homography


def transform_points(homography, points):
    point_array = np.array(points, dtype=np.float32).reshape(-1, 1, 2)
    transformed = cv2.perspectiveTransform(point_array, homography)
    return transformed.reshape(-1, 2)


def marker_points_to_wall(marker, homography):
    image_corners = [
        normalize_point(corner, f"marker {marker.get('id')} corner")
        for corner in marker["corners"]
    ]
    image_center = normalize_point(
        marker["center"],
        f"marker {marker.get('id')} center",
    )

    transformed_corners = transform_points(homography, image_corners)
    transformed_center = transform_points(homography, [image_center])[0]

    return {
        "id": marker["id"],
        "image": {
            "corners": marker["corners"],
            "center": marker["center"],
        },
        "wall_mm": {
            "corners": [
                {"x": round(float(point[0]), 3), "y": round(float(point[1]), 3)}
                for point in transformed_corners
            ],
            "center": {
                "x": round(float(transformed_center[0]), 3),
                "y": round(float(transformed_center[1]), 3),
            },
        },
    }


def build_single_reference_metadata(reference_marker, marker_size_mm, origin_mode):
    return {
        "mode": "single_reference_marker",
        "id": reference_marker["id"],
        "marker_size_mm": marker_size_mm,
        "origin_mode": origin_mode,
    }


def build_fixed_reference_metadata(reference_marker_ids, marker_size_mm):
    reference_count = len(reference_marker_ids)
    return {
        "mode": f"fixed_{reference_count}_reference_markers",
        "ids": list(reference_marker_ids),
        "marker_size_mm": marker_size_mm,
        "origin_mode": "bottom_left",
        "wall_width_mm": FIXED_WALL_WIDTH_MM,
        "wall_height_mm": FIXED_WALL_HEIGHT_MM,
        "layouts": {
            str(marker_id): FIXED_REFERENCE_MARKER_LAYOUTS[marker_id]
            for marker_id in reference_marker_ids
        },
    }


def build_wall_payload(
    detection_payload,
    marker_size_mm,
    reference_marker=None,
    origin_mode="top_left",
    reference_marker_ids=None,
):
    markers = detection_payload["markers"]

    normalized_reference_ids = normalize_reference_marker_ids(reference_marker_ids)
    if normalized_reference_ids is not None:
        reference_markers, _ = get_reference_markers_by_ids(
            markers,
            normalized_reference_ids,
            require_all=True,
        )
        homography = compute_fixed_reference_homography(
            reference_markers,
            normalized_reference_ids,
        )
        reference_metadata = build_fixed_reference_metadata(
            normalized_reference_ids,
            marker_size_mm,
        )
        y_axis = "up"
    else:
        homography = compute_homography(reference_marker, marker_size_mm, origin_mode)
        reference_metadata = build_single_reference_metadata(
            reference_marker,
            marker_size_mm,
            origin_mode,
        )
        y_axis = "up" if origin_mode == "bottom_left" else "down"

    transformed_markers = [
        marker_points_to_wall(marker, homography) for marker in markers
    ]

    return {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "source_detection": detection_payload.get("source"),
        "dictionary": detection_payload.get("dictionary"),
        "image_size": detection_payload.get("image_size"),
        "reference_marker": reference_metadata,
        "coordinate_system": {
            "unit": "mm",
            "x_axis": "right",
            "y_axis": y_axis,
            "plane": "wall_plane_marker_local",
            "wall_width_mm": FIXED_WALL_WIDTH_MM,
            "wall_height_mm": FIXED_WALL_HEIGHT_MM,
        },
        "marker_count": len(transformed_markers),
        "markers": transformed_markers,
    }


def convert_detection_to_wall_payload(
    detection_payload,
    marker_size_mm,
    origin_marker_id=None,
    origin_mode="top_left",
    reference_marker_ids=None,
):
    normalized_reference_ids = normalize_reference_marker_ids(reference_marker_ids)
    reference_marker = None
    if normalized_reference_ids is None:
        reference_marker = get_reference_marker(
            detection_payload["markers"], origin_marker_id
        )
    return build_wall_payload(
        detection_payload=detection_payload,
        marker_size_mm=marker_size_mm,
        reference_marker=reference_marker,
        origin_mode=origin_mode,
        reference_marker_ids=normalized_reference_ids,
    )


def print_wall_results(payload):
    reference = payload["reference_marker"]
    if "ids" in reference:
        layout_summary = "+".join(
            f"{marker_id}:{reference['layouts'][str(marker_id)]}"
            for marker_id in reference["ids"]
        )
        print(
            "[INFO] 已生成墙面坐标: "
            f"reference_marker_ids={reference['ids']}, "
            f"marker_size_mm={reference['marker_size_mm']}, "
            f"origin={reference['origin_mode']}, "
            f"layout={layout_summary}"
        )
    else:
        print(
            "[INFO] 已生成墙面坐标: "
            f"reference_marker_id={reference['id']}, "
            f"marker_size_mm={reference['marker_size_mm']}, "
            f"origin={reference['origin_mode']}"
        )

    for marker in payload["markers"]:
        center = marker["wall_mm"]["center"]
        print(
            f"  - ID: {marker['id']}, "
            f"wall_center_mm=({center['x']:.3f}, {center['y']:.3f})"
        )


def build_output_path(input_path, output_dir):
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    return output_dir / f"{input_path.stem}_wall_coords_{timestamp}.json"


def save_wall_json(payload, input_path, output_dir):
    output_path = build_output_path(input_path, output_dir)
    output_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"[INFO] 已保存墙面坐标 JSON: {output_path}")
    return output_path


def save_wall_json_with_prefix(payload, prefix, output_dir):
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    output_path = output_dir / f"{prefix}_wall_coords_{timestamp}.json"
    output_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"[INFO] 已保存墙面坐标 JSON: {output_path}")
    return output_path


def compute_marker_wall_coords(
    marker_list,
    reference_marker=None,
    marker_size_mm=None,
    origin_mode="top_left",
    reference_marker_ids=None,
):
    """
    Compute wall coordinates for a list of markers given a reference marker.

    This function is designed for real-time use in the camera pipeline.

    Args:
        marker_list: List of marker dicts with 'id', 'corners', 'center'
        reference_marker: Reference marker dict (typically used for single-marker homography)
        marker_size_mm: Physical marker size in millimeters
        origin_mode: Origin mode ('top_left', 'center', or 'bottom_left')
        reference_marker_ids: Optional fixed reference marker IDs for dual-reference mapping

    Returns:
        List of marker dicts with 'id' and 'wall_mm' containing transformed coordinates
    """
    normalized_reference_ids = normalize_reference_marker_ids(reference_marker_ids)
    if normalized_reference_ids is not None:
        reference_markers, _ = get_reference_markers_by_ids(
            marker_list,
            normalized_reference_ids,
            require_all=True,
        )
        homography = compute_fixed_reference_homography(
            reference_markers,
            normalized_reference_ids,
        )
    else:
        homography = compute_homography(reference_marker, marker_size_mm, origin_mode)

    transformed_markers = [
        marker_points_to_wall(marker, homography) for marker in marker_list
    ]
    return transformed_markers


def main():
    args = parse_args()

    try:
        input_path = validate_input_path(args.input)
        detection_payload = load_detection_json(input_path)
        output_dir = ensure_output_dir()

        wall_payload = convert_detection_to_wall_payload(
            detection_payload=detection_payload,
            marker_size_mm=args.marker_size_mm,
            origin_marker_id=args.origin_marker_id,
            origin_mode=args.origin,
            reference_marker_ids=args.reference_marker_ids,
        )

        print_wall_results(wall_payload)
        save_wall_json(wall_payload, input_path, output_dir)

    except Exception as exc:
        print(f"[ERROR] {exc}")
        sys.exit(1)


if __name__ == "__main__":
    main()
