import argparse
import json
import sys
import time
from pathlib import Path

import cv2
import numpy as np


OUTPUT_DIR = Path("outputs/wall_coords")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Convert Aruco detection JSON into wall-plane coordinates."
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to detection JSON generated by aruco_detect.py",
    )
    parser.add_argument(
        "--marker-size-mm",
        type=float,
        required=True,
        help="Physical size of the reference Aruco marker in millimeters",
    )
    parser.add_argument(
        "--origin-marker-id",
        type=int,
        help="Marker ID used as wall coordinate origin. Default: first detected marker",
    )
    parser.add_argument(
        "--origin",
        choices=["top_left", "center"],
        default="top_left",
        help="Wall coordinate origin on the reference marker. Default: top_left",
    )
    return parser.parse_args()


def ensure_output_dir(output_dir=OUTPUT_DIR):
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def validate_input_path(input_path):
    path = Path(input_path)
    if not path.exists():
        raise FileNotFoundError(f"输入 JSON 路径不存在: {path}")
    if not path.is_file():
        raise FileNotFoundError(f"输入路径不是文件: {path}")
    return path


def load_detection_json(input_path):
    try:
        payload = json.loads(input_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"JSON 解析失败: {exc}") from exc

    if "markers" not in payload:
        raise RuntimeError("输入 JSON 缺少 markers 字段")

    return payload


def get_reference_marker(markers, origin_marker_id):
    if not markers:
        raise RuntimeError("检测结果中没有 marker，无法生成墙面坐标")

    if origin_marker_id is None:
        return markers[0]

    for marker in markers:
        if marker.get("id") == origin_marker_id:
            return marker

    raise RuntimeError(f"未找到 origin marker id: {origin_marker_id}")


def corners_to_array(marker):
    corners = marker.get("corners", [])
    if len(corners) != 4:
        raise RuntimeError(f"marker {marker.get('id')} 的 corners 数量不是 4")

    return np.array(
        [[corner["x"], corner["y"]] for corner in corners],
        dtype=np.float32,
    )


def build_reference_wall_points(marker_size_mm, origin_mode):
    if marker_size_mm <= 0:
        raise ValueError("marker-size-mm 必须大于 0")

    if origin_mode == "center":
        half = marker_size_mm / 2.0
        return np.array(
            [
                [-half, -half],
                [half, -half],
                [half, half],
                [-half, half],
            ],
            dtype=np.float32,
        )

    return np.array(
        [
            [0.0, 0.0],
            [marker_size_mm, 0.0],
            [marker_size_mm, marker_size_mm],
            [0.0, marker_size_mm],
        ],
        dtype=np.float32,
    )


def compute_homography(reference_marker, marker_size_mm, origin_mode):
    image_points = corners_to_array(reference_marker)
    wall_points = build_reference_wall_points(marker_size_mm, origin_mode)

    homography = cv2.getPerspectiveTransform(image_points, wall_points)
    if homography is None:
        raise RuntimeError("单应性矩阵计算失败")

    return homography


def transform_points(homography, points):
    point_array = np.array(points, dtype=np.float32).reshape(-1, 1, 2)
    transformed = cv2.perspectiveTransform(point_array, homography)
    return transformed.reshape(-1, 2)


def marker_points_to_wall(marker, homography):
    image_corners = [(corner["x"], corner["y"]) for corner in marker["corners"]]
    image_center = (marker["center"]["x"], marker["center"]["y"])

    transformed_corners = transform_points(homography, image_corners)
    transformed_center = transform_points(homography, [image_center])[0]

    return {
        "id": marker["id"],
        "image": {
            "corners": marker["corners"],
            "center": marker["center"],
        },
        "wall_mm": {
            "corners": [
                {"x": round(float(point[0]), 3), "y": round(float(point[1]), 3)}
                for point in transformed_corners
            ],
            "center": {
                "x": round(float(transformed_center[0]), 3),
                "y": round(float(transformed_center[1]), 3),
            },
        },
    }


def build_wall_payload(detection_payload, marker_size_mm, reference_marker, origin_mode):
    homography = compute_homography(reference_marker, marker_size_mm, origin_mode)
    markers = detection_payload["markers"]

    transformed_markers = [
        marker_points_to_wall(marker, homography) for marker in markers
    ]

    return {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "source_detection": detection_payload.get("source"),
        "dictionary": detection_payload.get("dictionary"),
        "image_size": detection_payload.get("image_size"),
        "reference_marker": {
            "id": reference_marker["id"],
            "marker_size_mm": marker_size_mm,
            "origin_mode": origin_mode,
        },
        "coordinate_system": {
            "unit": "mm",
            "x_axis": "right",
            "y_axis": "down",
            "plane": "wall_plane_marker_local",
        },
        "marker_count": len(transformed_markers),
        "markers": transformed_markers,
    }


def convert_detection_to_wall_payload(
    detection_payload, marker_size_mm, origin_marker_id=None, origin_mode="top_left"
):
    reference_marker = get_reference_marker(
        detection_payload["markers"], origin_marker_id
    )
    return build_wall_payload(
        detection_payload=detection_payload,
        marker_size_mm=marker_size_mm,
        reference_marker=reference_marker,
        origin_mode=origin_mode,
    )


def print_wall_results(payload):
    reference = payload["reference_marker"]
    print(
        "[INFO] 已生成墙面坐标: "
        f"reference_marker_id={reference['id']}, "
        f"marker_size_mm={reference['marker_size_mm']}, "
        f"origin={reference['origin_mode']}"
    )

    for marker in payload["markers"]:
        center = marker["wall_mm"]["center"]
        print(
            f"  - ID: {marker['id']}, "
            f"wall_center_mm=({center['x']:.3f}, {center['y']:.3f})"
        )


def build_output_path(input_path, output_dir):
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    return output_dir / f"{input_path.stem}_wall_coords_{timestamp}.json"


def save_wall_json(payload, input_path, output_dir):
    output_path = build_output_path(input_path, output_dir)
    output_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"[INFO] 已保存墙面坐标 JSON: {output_path}")
    return output_path


def save_wall_json_with_prefix(payload, prefix, output_dir):
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    output_path = output_dir / f"{prefix}_wall_coords_{timestamp}.json"
    output_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"[INFO] 已保存墙面坐标 JSON: {output_path}")
    return output_path


def main():
    args = parse_args()

    try:
        input_path = validate_input_path(args.input)
        detection_payload = load_detection_json(input_path)
        output_dir = ensure_output_dir()

        wall_payload = convert_detection_to_wall_payload(
            detection_payload=detection_payload,
            marker_size_mm=args.marker_size_mm,
            origin_marker_id=args.origin_marker_id,
            origin_mode=args.origin,
        )

        print_wall_results(wall_payload)
        save_wall_json(wall_payload, input_path, output_dir)

    except Exception as exc:
        print(f"[ERROR] {exc}")
        sys.exit(1)


if __name__ == "__main__":
    main()
