import argparse
import json
import sys
import time
from pathlib import Path


OUTPUT_DIR = Path("outputs/projection_targets")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Build projection target points from wall coordinate JSON."
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to wall coordinate JSON generated by aruco_to_wall_coords.py",
    )
    parser.add_argument(
        "--target-type",
        choices=["centers", "corners", "all"],
        default="centers",
        help="Which marker points to export. Default: centers",
    )
    parser.add_argument(
        "--marker-ids",
        nargs="+",
        type=int,
        help="Optional marker IDs to include. Default: include all markers",
    )
    parser.add_argument(
        "--label-prefix",
        default="target",
        help="Prefix used when naming exported targets. Default: target",
    )
    return parser.parse_args()


def ensure_output_dir(output_dir=OUTPUT_DIR):
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def validate_input_path(input_path):
    path = Path(input_path)
    if not path.exists():
        raise FileNotFoundError(f"输入 JSON 路径不存在: {path}")
    if not path.is_file():
        raise FileNotFoundError(f"输入路径不是文件: {path}")
    return path


def load_wall_json(input_path):
    try:
        payload = json.loads(input_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"JSON 解析失败: {exc}") from exc

    if "markers" not in payload:
        raise RuntimeError("输入 JSON 缺少 markers 字段")

    return payload


def filter_markers(markers, marker_ids):
    if not marker_ids:
        return markers

    selected = [marker for marker in markers if marker.get("id") in marker_ids]
    if not selected:
        raise RuntimeError(f"没有找到指定的 marker IDs: {marker_ids}")
    return selected


def build_center_target(marker, label_prefix):
    center = marker["wall_mm"]["center"]
    return {
        "label": f"{label_prefix}_marker_{marker['id']}_center",
        "marker_id": marker["id"],
        "point_type": "center",
        "wall_mm": {
            "x": center["x"],
            "y": center["y"],
        },
    }


def build_corner_targets(marker, label_prefix):
    corner_names = ["top_left", "top_right", "bottom_right", "bottom_left"]
    targets = []

    for corner_name, corner in zip(corner_names, marker["wall_mm"]["corners"]):
        targets.append(
            {
                "label": f"{label_prefix}_marker_{marker['id']}_{corner_name}",
                "marker_id": marker["id"],
                "point_type": corner_name,
                "wall_mm": {
                    "x": corner["x"],
                    "y": corner["y"],
                },
            }
        )

    return targets


def build_targets(markers, target_type, label_prefix):
    targets = []

    for marker in markers:
        if target_type in ("centers", "all"):
            targets.append(build_center_target(marker, label_prefix))

        if target_type in ("corners", "all"):
            targets.extend(build_corner_targets(marker, label_prefix))

    if not targets:
        raise RuntimeError("没有可导出的目标点")

    return targets


def build_projection_payload(wall_payload, targets, target_type):
    return {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "source_wall_coords": wall_payload.get("source_detection"),
        "dictionary": wall_payload.get("dictionary"),
        "reference_marker": wall_payload.get("reference_marker"),
        "coordinate_system": wall_payload.get("coordinate_system"),
        "target_type": target_type,
        "target_count": len(targets),
        "targets": targets,
    }


def convert_wall_to_projection_payload(
    wall_payload, target_type="centers", marker_ids=None, label_prefix="target"
):
    markers = filter_markers(wall_payload["markers"], marker_ids)
    targets = build_targets(markers, target_type, label_prefix)
    return build_projection_payload(
        wall_payload=wall_payload,
        targets=targets,
        target_type=target_type,
    )


def print_projection_targets(payload):
    print(
        f"[INFO] 已生成投影目标点: type={payload['target_type']}, "
        f"count={payload['target_count']}"
    )

    for target in payload["targets"]:
        point = target["wall_mm"]
        print(
            f"  - {target['label']}: "
            f"({point['x']:.3f}, {point['y']:.3f}) mm"
        )


def build_output_path(input_path, output_dir):
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    return output_dir / f"{input_path.stem}_projection_targets_{timestamp}.json"


def save_projection_json(payload, input_path, output_dir):
    output_path = build_output_path(input_path, output_dir)
    output_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"[INFO] 已保存投影目标点 JSON: {output_path}")
    return output_path


def save_projection_json_with_prefix(payload, prefix, output_dir):
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    output_path = output_dir / f"{prefix}_projection_targets_{timestamp}.json"
    output_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"[INFO] 已保存投影目标点 JSON: {output_path}")
    return output_path


def main():
    args = parse_args()

    try:
        input_path = validate_input_path(args.input)
        wall_payload = load_wall_json(input_path)
        output_dir = ensure_output_dir()

        projection_payload = convert_wall_to_projection_payload(
            wall_payload=wall_payload,
            target_type=args.target_type,
            marker_ids=args.marker_ids,
            label_prefix=args.label_prefix,
        )

        print_projection_targets(projection_payload)
        save_projection_json(projection_payload, input_path, output_dir)

    except Exception as exc:
        print(f"[ERROR] {exc}")
        sys.exit(1)


if __name__ == "__main__":
    main()
