import argparse
import json
import sys
import time
from pathlib import Path


OUTPUT_DIR = Path("outputs/projection_executor")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Build a hardware-agnostic execution queue from projection targets."
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to projection target JSON generated by projection_targets.py",
    )
    parser.add_argument(
        "--dwell-ms",
        type=int,
        default=500,
        help="Laser dwell time per target in milliseconds. Default: 500",
    )
    parser.add_argument(
        "--travel-ms",
        type=int,
        default=150,
        help="Estimated travel time between targets in milliseconds. Default: 150",
    )
    parser.add_argument(
        "--settle-ms",
        type=int,
        default=80,
        help="Settling time after movement in milliseconds. Default: 80",
    )
    parser.add_argument(
        "--repeat",
        type=int,
        default=1,
        help="How many times to repeat the whole target sequence. Default: 1",
    )
    parser.add_argument(
        "--laser-power",
        type=float,
        default=1.0,
        help="Normalized laser power value in range [0.0, 1.0]. Default: 1.0",
    )
    parser.add_argument(
        "--device-name",
        default="laser_projector_stub",
        help="Execution device name written into the queue metadata",
    )
    return parser.parse_args()


def ensure_output_dir(output_dir=OUTPUT_DIR):
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def validate_input_path(input_path):
    path = Path(input_path)
    if not path.exists():
        raise FileNotFoundError(f"输入 JSON 路径不存在: {path}")
    if not path.is_file():
        raise FileNotFoundError(f"输入路径不是文件: {path}")
    return path


def load_projection_json(input_path):
    try:
        payload = json.loads(input_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"JSON 解析失败: {exc}") from exc

    if "targets" not in payload:
        raise RuntimeError("输入 JSON 缺少 targets 字段")

    return payload


def validate_args(args):
    if args.dwell_ms < 0:
        raise ValueError("dwell-ms 不能小于 0")
    if args.travel_ms < 0:
        raise ValueError("travel-ms 不能小于 0")
    if args.settle_ms < 0:
        raise ValueError("settle-ms 不能小于 0")
    if args.repeat <= 0:
        raise ValueError("repeat 必须大于 0")
    if not 0.0 <= args.laser_power <= 1.0:
        raise ValueError("laser-power 必须在 0.0 到 1.0 之间")


def build_move_step(target, step_index, cycle_index, travel_ms):
    point = target["wall_mm"]
    return {
        "step_index": step_index,
        "cycle_index": cycle_index,
        "action": "move",
        "target_label": target["label"],
        "marker_id": target["marker_id"],
        "point_type": target["point_type"],
        "wall_mm": {
            "x": point["x"],
            "y": point["y"],
        },
        "duration_ms": travel_ms,
    }


def build_settle_step(target, step_index, cycle_index, settle_ms):
    point = target["wall_mm"]
    return {
        "step_index": step_index,
        "cycle_index": cycle_index,
        "action": "settle",
        "target_label": target["label"],
        "marker_id": target["marker_id"],
        "point_type": target["point_type"],
        "wall_mm": {
            "x": point["x"],
            "y": point["y"],
        },
        "duration_ms": settle_ms,
    }


def build_laser_step(target, step_index, cycle_index, dwell_ms, laser_power):
    point = target["wall_mm"]
    return {
        "step_index": step_index,
        "cycle_index": cycle_index,
        "action": "laser_on",
        "target_label": target["label"],
        "marker_id": target["marker_id"],
        "point_type": target["point_type"],
        "wall_mm": {
            "x": point["x"],
            "y": point["y"],
        },
        "duration_ms": dwell_ms,
        "laser_power": laser_power,
    }


def build_laser_off_step(target, step_index, cycle_index):
    point = target["wall_mm"]
    return {
        "step_index": step_index,
        "cycle_index": cycle_index,
        "action": "laser_off",
        "target_label": target["label"],
        "marker_id": target["marker_id"],
        "point_type": target["point_type"],
        "wall_mm": {
            "x": point["x"],
            "y": point["y"],
        },
        "duration_ms": 0,
    }


def build_execution_steps(targets, dwell_ms, travel_ms, settle_ms, repeat, laser_power):
    steps = []
    step_index = 1

    for cycle_index in range(1, repeat + 1):
        for target in targets:
            steps.append(build_move_step(target, step_index, cycle_index, travel_ms))
            step_index += 1

            if settle_ms > 0:
                steps.append(
                    build_settle_step(target, step_index, cycle_index, settle_ms)
                )
                step_index += 1

            if dwell_ms > 0:
                steps.append(
                    build_laser_step(
                        target, step_index, cycle_index, dwell_ms, laser_power
                    )
                )
                step_index += 1

            steps.append(build_laser_off_step(target, step_index, cycle_index))
            step_index += 1

    return steps


def build_execution_payload(projection_payload, args):
    targets = projection_payload["targets"]
    steps = build_execution_steps(
        targets=targets,
        dwell_ms=args.dwell_ms,
        travel_ms=args.travel_ms,
        settle_ms=args.settle_ms,
        repeat=args.repeat,
        laser_power=args.laser_power,
    )
    total_duration_ms = sum(step["duration_ms"] for step in steps)

    return {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "device_name": args.device_name,
        "source_projection_targets": projection_payload.get("source_wall_coords"),
        "reference_marker": projection_payload.get("reference_marker"),
        "coordinate_system": projection_payload.get("coordinate_system"),
        "queue_config": {
            "repeat": args.repeat,
            "dwell_ms": args.dwell_ms,
            "travel_ms": args.travel_ms,
            "settle_ms": args.settle_ms,
            "laser_power": args.laser_power,
        },
        "target_count": len(targets),
        "step_count": len(steps),
        "estimated_total_duration_ms": total_duration_ms,
        "steps": steps,
    }


def convert_projection_to_execution_payload(
    projection_payload,
    dwell_ms=500,
    travel_ms=150,
    settle_ms=80,
    repeat=1,
    laser_power=1.0,
    device_name="laser_projector_stub",
):
    class Args:
        pass

    args = Args()
    args.dwell_ms = dwell_ms
    args.travel_ms = travel_ms
    args.settle_ms = settle_ms
    args.repeat = repeat
    args.laser_power = laser_power
    args.device_name = device_name
    validate_args(args)
    return build_execution_payload(projection_payload, args)


def print_execution_summary(payload):
    print(
        f"[INFO] 已生成执行队列: steps={payload['step_count']}, "
        f"targets={payload['target_count']}, "
        f"estimated_total_duration_ms={payload['estimated_total_duration_ms']}"
    )

    preview_steps = payload["steps"][:12]
    for step in preview_steps:
        point = step["wall_mm"]
        print(
            f"  - step={step['step_index']}, cycle={step['cycle_index']}, "
            f"action={step['action']}, target={step['target_label']}, "
            f"xy=({point['x']:.3f}, {point['y']:.3f}), duration_ms={step['duration_ms']}"
        )

    remaining = payload["step_count"] - len(preview_steps)
    if remaining > 0:
        print(f"  ... 其余 {remaining} 个步骤已写入 JSON")


def build_output_path(input_path, output_dir):
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    return output_dir / f"{input_path.stem}_execution_queue_{timestamp}.json"


def save_execution_json(payload, input_path, output_dir):
    output_path = build_output_path(input_path, output_dir)
    output_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"[INFO] 已保存执行队列 JSON: {output_path}")
    return output_path


def save_execution_json_with_prefix(payload, prefix, output_dir):
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    output_path = output_dir / f"{prefix}_execution_queue_{timestamp}.json"
    output_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"[INFO] 已保存执行队列 JSON: {output_path}")
    return output_path


def main():
    args = parse_args()

    try:
        validate_args(args)
        input_path = validate_input_path(args.input)
        projection_payload = load_projection_json(input_path)
        output_dir = ensure_output_dir()

        execution_payload = build_execution_payload(projection_payload, args)
        print_execution_summary(execution_payload)
        save_execution_json(execution_payload, input_path, output_dir)

    except Exception as exc:
        print(f"[ERROR] {exc}")
        sys.exit(1)


if __name__ == "__main__":
    main()
