import argparse
import json
import sys
import time
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description="Play back an execution queue in the terminal for verification."
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to execution queue JSON generated by projection_executor_stub.py",
    )
    parser.add_argument(
        "--speed",
        type=float,
        default=1.0,
        help="Playback speed multiplier. Default: 1.0",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print steps without waiting for their full duration",
    )
    parser.add_argument(
        "--max-steps",
        type=int,
        help="Optional maximum number of steps to play",
    )
    return parser.parse_args()


def validate_args(args):
    if args.speed <= 0:
        raise ValueError("speed 必须大于 0")
    if args.max_steps is not None and args.max_steps <= 0:
        raise ValueError("max-steps 必须大于 0")


def validate_input_path(input_path):
    path = Path(input_path)
    if not path.exists():
        raise FileNotFoundError(f"输入 JSON 路径不存在: {path}")
    if not path.is_file():
        raise FileNotFoundError(f"输入路径不是文件: {path}")
    return path


def load_execution_json(input_path):
    try:
        payload = json.loads(input_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"JSON 解析失败: {exc}") from exc

    if "steps" not in payload:
        raise RuntimeError("输入 JSON 缺少 steps 字段")

    return payload


def get_steps_to_play(payload, max_steps):
    steps = payload["steps"]
    if max_steps is None:
        return steps
    return steps[:max_steps]


def format_step(step, adjusted_duration_ms):
    point = step["wall_mm"]
    extras = []

    if "laser_power" in step:
        extras.append(f"power={step['laser_power']}")

    extra_text = f", {' '.join(extras)}" if extras else ""
    return (
        f"[PLAY] step={step['step_index']} cycle={step['cycle_index']} "
        f"action={step['action']} target={step['target_label']} "
        f"xy=({point['x']:.3f}, {point['y']:.3f}) "
        f"duration_ms={adjusted_duration_ms}{extra_text}"
    )


def wait_for_step(duration_ms, dry_run):
    if duration_ms <= 0:
        return

    if dry_run:
        return

    time.sleep(duration_ms / 1000.0)


def play_steps(steps, speed, dry_run):
    played_duration_ms = 0
    start_time = time.time()

    for step in steps:
        adjusted_duration_ms = int(round(step["duration_ms"] / speed))
        print(format_step(step, adjusted_duration_ms))
        wait_for_step(adjusted_duration_ms, dry_run)
        played_duration_ms += adjusted_duration_ms

    elapsed_wall_time_ms = int(round((time.time() - start_time) * 1000))
    return played_duration_ms, elapsed_wall_time_ms


def print_queue_summary(payload, steps, speed, dry_run):
    print(
        f"[INFO] 开始播放执行队列: device={payload.get('device_name')}, "
        f"steps={len(steps)}/{payload.get('step_count')}, speed={speed}, dry_run={dry_run}"
    )
    print(
        f"[INFO] source={payload.get('source_projection_targets')}, "
        f"estimated_total_duration_ms={payload.get('estimated_total_duration_ms')}"
    )


def print_completion_summary(played_duration_ms, elapsed_wall_time_ms, dry_run):
    print(
        f"[INFO] 播放完成: scheduled_duration_ms={played_duration_ms}, "
        f"elapsed_wall_time_ms={elapsed_wall_time_ms}, dry_run={dry_run}"
    )


def main():
    args = parse_args()

    try:
        validate_args(args)
        input_path = validate_input_path(args.input)
        payload = load_execution_json(input_path)
        steps = get_steps_to_play(payload, args.max_steps)

        if not steps:
            raise RuntimeError("执行队列为空，无法播放")

        print_queue_summary(payload, steps, args.speed, args.dry_run)
        played_duration_ms, elapsed_wall_time_ms = play_steps(
            steps=steps,
            speed=args.speed,
            dry_run=args.dry_run,
        )
        print_completion_summary(played_duration_ms, elapsed_wall_time_ms, args.dry_run)

    except KeyboardInterrupt:
        print("\n[INFO] 播放已被手动中断。")
        sys.exit(130)
    except Exception as exc:
        print(f"[ERROR] {exc}")
        sys.exit(1)


if __name__ == "__main__":
    main()
