import argparse
import json
import sys
import time
from pathlib import Path

import cv2
import numpy as np


OUTPUT_DIR = Path("outputs/projection_simulator")
WINDOW_NAME = "Projection Simulator"
CANVAS_WIDTH = 1280
CANVAS_HEIGHT = 960
MARGIN = 90


def parse_args():
    parser = argparse.ArgumentParser(
        description="Simulate projection targets on a 2D wall-plane canvas."
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to projection target JSON generated by projection_targets.py",
    )
    parser.add_argument(
        "--connect-order",
        action="store_true",
        help="Draw lines between targets following JSON order",
    )
    parser.add_argument(
        "--show-labels",
        action="store_true",
        help="Show target labels next to each point",
    )
    return parser.parse_args()


def ensure_output_dir(output_dir=OUTPUT_DIR):
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def validate_input_path(input_path):
    path = Path(input_path)
    if not path.exists():
        raise FileNotFoundError(f"输入 JSON 路径不存在: {path}")
    if not path.is_file():
        raise FileNotFoundError(f"输入路径不是文件: {path}")
    return path


def load_projection_json(input_path):
    try:
        payload = json.loads(input_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"JSON 解析失败: {exc}") from exc

    if "targets" not in payload:
        raise RuntimeError("输入 JSON 缺少 targets 字段")

    return payload


def collect_points(targets):
    if not targets:
        raise RuntimeError("projection targets 为空，无法模拟")
    return [(target["wall_mm"]["x"], target["wall_mm"]["y"]) for target in targets]


def compute_bounds(points):
    xs = [point[0] for point in points]
    ys = [point[1] for point in points]
    min_x = min(xs)
    max_x = max(xs)
    min_y = min(ys)
    max_y = max(ys)

    if min_x == max_x:
        max_x += 1.0
    if min_y == max_y:
        max_y += 1.0

    return min_x, max_x, min_y, max_y


def build_transform(bounds):
    min_x, max_x, min_y, max_y = bounds
    usable_width = CANVAS_WIDTH - 2 * MARGIN
    usable_height = CANVAS_HEIGHT - 2 * MARGIN
    scale = min(
        usable_width / (max_x - min_x),
        usable_height / (max_y - min_y),
    )
    return min_x, min_y, scale


def wall_to_canvas(point, bounds, transform):
    min_x, max_x, min_y, max_y = bounds
    origin_x, origin_y, scale = transform
    width_mm = max_x - min_x
    height_mm = max_y - min_y
    used_width = width_mm * scale
    used_height = height_mm * scale
    offset_x = (CANVAS_WIDTH - used_width) / 2.0
    offset_y = (CANVAS_HEIGHT - used_height) / 2.0

    x = int(round(offset_x + (point[0] - origin_x) * scale))
    y = int(round(offset_y + (point[1] - origin_y) * scale))
    return x, y


def create_canvas():
    canvas = np.full((CANVAS_HEIGHT, CANVAS_WIDTH, 3), 248, dtype=np.uint8)
    cv2.rectangle(
        canvas,
        (0, 0),
        (CANVAS_WIDTH - 1, CANVAS_HEIGHT - 1),
        (220, 220, 220),
        2,
    )
    return canvas


def draw_header(canvas, payload):
    reference = payload.get("reference_marker", {})
    lines = [
        "Projection Simulator",
        f"Source: {payload.get('source_wall_coords')}",
        f"Target type: {payload.get('target_type')}, count: {payload.get('target_count')}",
        f"Reference ID: {reference.get('id')}, origin: {reference.get('origin_mode')}",
    ]

    y = 32
    for index, line in enumerate(lines):
        cv2.putText(
            canvas,
            line,
            (20, y),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.72,
            (35, 35, 35),
            2 if index == 0 else 1,
            cv2.LINE_AA,
        )
        y += 28


def draw_axes(canvas, bounds, transform):
    min_x, max_x, min_y, max_y = bounds
    axis_color = (120, 120, 120)

    top_left = wall_to_canvas((min_x, min_y), bounds, transform)
    bottom_left = wall_to_canvas((min_x, max_y), bounds, transform)
    top_right = wall_to_canvas((max_x, min_y), bounds, transform)

    cv2.line(canvas, top_left, bottom_left, axis_color, 2)
    cv2.line(canvas, top_left, top_right, axis_color, 2)

    cv2.putText(
        canvas,
        "Y+",
        (bottom_left[0] - 10, bottom_left[1] + 28),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.7,
        axis_color,
        2,
        cv2.LINE_AA,
    )
    cv2.putText(
        canvas,
        "X+",
        (top_right[0] + 8, top_right[1] + 5),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.7,
        axis_color,
        2,
        cv2.LINE_AA,
    )


def draw_projection_path(canvas, targets, bounds, transform):
    if len(targets) < 2:
        return

    points = [
        wall_to_canvas((target["wall_mm"]["x"], target["wall_mm"]["y"]), bounds, transform)
        for target in targets
    ]

    for start, end in zip(points, points[1:]):
        cv2.line(canvas, start, end, (255, 170, 0), 2, cv2.LINE_AA)


def draw_targets(canvas, targets, bounds, transform, show_labels):
    for index, target in enumerate(targets, start=1):
        wall_point = (target["wall_mm"]["x"], target["wall_mm"]["y"])
        canvas_point = wall_to_canvas(wall_point, bounds, transform)

        cv2.circle(canvas, canvas_point, 9, (0, 0, 255), -1)
        cv2.circle(canvas, canvas_point, 16, (0, 180, 255), 2)

        cv2.putText(
            canvas,
            str(index),
            (canvas_point[0] - 8, canvas_point[1] - 14),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (20, 20, 20),
            2,
            cv2.LINE_AA,
        )

        cv2.putText(
            canvas,
            f"({wall_point[0]:.1f}, {wall_point[1]:.1f}) mm",
            (canvas_point[0] + 12, canvas_point[1] + 6),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.45,
            (45, 45, 45),
            1,
            cv2.LINE_AA,
        )

        if show_labels:
            cv2.putText(
                canvas,
                target["label"],
                (canvas_point[0] + 12, canvas_point[1] + 26),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.45,
                (80, 80, 80),
                1,
                cv2.LINE_AA,
            )


def render_projection_preview(payload, connect_order, show_labels):
    targets = payload["targets"]
    bounds = compute_bounds(collect_points(targets))
    transform = build_transform(bounds)

    canvas = create_canvas()
    draw_header(canvas, payload)
    draw_axes(canvas, bounds, transform)

    if connect_order:
        draw_projection_path(canvas, targets, bounds, transform)

    draw_targets(canvas, targets, bounds, transform, show_labels)
    return canvas


def print_projection_summary(payload):
    print(
        f"[INFO] 模拟投影目标点: type={payload.get('target_type')}, "
        f"count={payload.get('target_count')}"
    )
    for index, target in enumerate(payload["targets"], start=1):
        point = target["wall_mm"]
        print(
            f"  - #{index} {target['label']}: "
            f"({point['x']:.3f}, {point['y']:.3f}) mm"
        )


def build_output_path(input_path, output_dir):
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    return output_dir / f"{input_path.stem}_simulation_{timestamp}.png"


def save_preview(image, input_path, output_dir):
    output_path = build_output_path(input_path, output_dir)
    success = cv2.imwrite(str(output_path), image)
    if not success:
        raise RuntimeError(f"保存模拟图失败: {output_path}")
    print(f"[INFO] 已保存投影模拟图: {output_path}")


def show_preview(image, input_path, output_dir):
    print("[INFO] 按 'q' 退出窗口，按 's' 保存模拟图。")
    while True:
        cv2.imshow(WINDOW_NAME, image)
        key = cv2.waitKey(0) & 0xFF

        if key == ord("q"):
            print("[INFO] Quit.")
            break
        if key == ord("s"):
            save_preview(image, input_path, output_dir)

    cv2.destroyAllWindows()


def main():
    args = parse_args()

    try:
        input_path = validate_input_path(args.input)
        payload = load_projection_json(input_path)
        output_dir = ensure_output_dir()

        print_projection_summary(payload)
        preview = render_projection_preview(
            payload=payload,
            connect_order=args.connect_order,
            show_labels=args.show_labels,
        )
        show_preview(preview, input_path, output_dir)

    except Exception as exc:
        print(f"[ERROR] {exc}")
        sys.exit(1)


if __name__ == "__main__":
    main()
