import argparse
import json
import sys
import time
import traceback
from pathlib import Path

import cv2
import numpy as np


OUTPUT_DIR = Path("outputs/wall_coords_viewer")
WINDOW_NAME = "Wall Coordinates Viewer"
CANVAS_WIDTH = 1200
CANVAS_HEIGHT = 900
MARGIN = 80
DEBUG_WALL_PREFIX = "[DEBUG_WALL]"
_debug_wall_point_types_seen = set()
_debug_wall_geometry_logs = 0
_debug_wall_exception_logs = 0


def parse_args():
    parser = argparse.ArgumentParser(
        description="Visualize wall-plane coordinates generated from Aruco markers."
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to wall coordinate JSON generated by aruco_to_wall_coords.py",
    )
    return parser.parse_args()


def ensure_output_dir(output_dir=OUTPUT_DIR):
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def validate_input_path(input_path):
    path = Path(input_path)
    if not path.exists():
        raise FileNotFoundError(f"输入 JSON 路径不存在: {path}")
    if not path.is_file():
        raise FileNotFoundError(f"输入路径不是文件: {path}")
    return path


def load_wall_json(input_path):
    try:
        payload = json.loads(input_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"JSON 解析失败: {exc}") from exc

    if "markers" not in payload:
        raise RuntimeError("输入 JSON 缺少 markers 字段")

    return payload


def debug_wall_log(message):
    print(f"{DEBUG_WALL_PREFIX} {message}")


def debug_wall_repr(value, limit=240):
    text = repr(value)
    if len(text) > limit:
        return f"{text[:limit]}..."
    return text


def debug_wall_log_new_point_type(point, context):
    point_type = type(point)
    if point_type in _debug_wall_point_types_seen:
        return

    _debug_wall_point_types_seen.add(point_type)
    debug_wall_log(
        f"viewer {context} point type={point_type} value={debug_wall_repr(point)}"
    )


def debug_wall_log_geometry(marker_id, wall_data):
    global _debug_wall_geometry_logs

    if _debug_wall_geometry_logs >= 5:
        return

    if isinstance(wall_data, dict):
        center = wall_data.get("center")
        corners = wall_data.get("corners")
        corner0 = corners[0] if isinstance(corners, (list, tuple)) and corners else None
        debug_wall_log(
            "viewer geometry "
            f"marker={marker_id} "
            f"wall_type={type(wall_data)} "
            f"center_type={type(center)} "
            f"corners_type={type(corners)} "
            f"corner0_type={type(corner0)}"
        )
    else:
        debug_wall_log(
            "viewer geometry "
            f"marker={marker_id} "
            f"wall_type={type(wall_data)} "
            f"value={debug_wall_repr(wall_data)}"
        )

    _debug_wall_geometry_logs += 1


def debug_wall_log_exception(stage, object_name, obj):
    global _debug_wall_exception_logs

    if _debug_wall_exception_logs >= 3:
        return

    debug_wall_log(f"viewer exception stage={stage}")
    debug_wall_log(f"viewer exception object={object_name}")
    debug_wall_log(f"viewer exception object type={type(obj)}")
    debug_wall_log(f"viewer exception object repr={debug_wall_repr(obj, limit=400)}")
    traceback_tail = traceback.format_exc().splitlines()[-6:]
    for line in traceback_tail:
        debug_wall_log(f"viewer traceback {line}")

    _debug_wall_exception_logs += 1


def normalize_point(point, context="point"):
    debug_wall_log_new_point_type(point, context)

    if isinstance(point, dict):
        x_value = point.get("x")
        y_value = point.get("y")
    elif isinstance(point, (tuple, list, np.ndarray)) and len(point) >= 2:
        x_value, y_value = point[0], point[1]
    else:
        raise RuntimeError(f"{context} 坐标格式不支持: {point!r}")

    if x_value is None or y_value is None:
        raise RuntimeError(f"{context} 缺少 x/y 坐标: {point!r}")

    return float(x_value), float(y_value)


def normalize_wall_geometry(wall_data, marker_id=None):
    context_prefix = f"marker {marker_id}" if marker_id is not None else "marker"
    debug_wall_log_geometry(marker_id, wall_data)

    if isinstance(wall_data, dict):
        raw_corners = wall_data.get("corners", [])
        raw_center = wall_data.get("center")

        if raw_corners or raw_center is not None:
            corners = [
                normalize_point(point, f"{context_prefix} corner")
                for point in raw_corners
            ]
            center = (
                normalize_point(raw_center, f"{context_prefix} center")
                if raw_center is not None
                else None
            )
        else:
            center = normalize_point(wall_data, f"{context_prefix} wall_mm")
            corners = []
    else:
        center = normalize_point(wall_data, f"{context_prefix} wall_mm")
        corners = []

    if center is None and corners:
        center_array = np.array(corners, dtype=np.float32)
        center = tuple(center_array.mean(axis=0).tolist())

    if center is None:
        raise RuntimeError(f"{context_prefix} 缺少可用的 wall 坐标")

    if not corners:
        corners = [center, center, center, center]

    return {
        "corners": corners,
        "center": center,
    }


def extract_marker_like_data(payload):
    if "markers" in payload:
        return payload["markers"], "markers"

    if "targets" in payload:
        markers = []
        for index, target in enumerate(payload["targets"]):
            point = normalize_point(target["wall_mm"], f"target {index} wall_mm")
            markers.append(
                {
                    "id": target.get("label", index),
                    "wall_mm": {
                        "corners": [point, point, point, point],
                        "center": point,
                    },
                }
            )
        return markers, "targets"

    raise RuntimeError("输入 JSON 缺少 markers 或 targets 字段")


def collect_wall_points(markers):
    points = []
    for marker in markers:
        wall = normalize_wall_geometry(marker.get("wall_mm", {}), marker.get("id"))
        points.extend(wall["corners"])
        points.append(wall["center"])
    return points


def compute_bounds(points):
    if not points:
        raise RuntimeError("wall 坐标为空，无法可视化")

    xs = [point[0] for point in points]
    ys = [point[1] for point in points]
    min_x = min(xs)
    max_x = max(xs)
    min_y = min(ys)
    max_y = max(ys)

    if min_x == max_x:
        max_x += 1.0
    if min_y == max_y:
        max_y += 1.0

    return min_x, max_x, min_y, max_y


def create_canvas():
    canvas = np.full((CANVAS_HEIGHT, CANVAS_WIDTH, 3), 245, dtype=np.uint8)
    cv2.rectangle(
        canvas,
        (0, 0),
        (CANVAS_WIDTH - 1, CANVAS_HEIGHT - 1),
        (210, 210, 210),
        2,
    )
    return canvas


def build_transform(bounds):
    min_x, max_x, min_y, max_y = bounds
    usable_width = CANVAS_WIDTH - 2 * MARGIN
    usable_height = CANVAS_HEIGHT - 2 * MARGIN
    scale_x = usable_width / (max_x - min_x)
    scale_y = usable_height / (max_y - min_y)
    scale = min(scale_x, scale_y)
    return min_x, min_y, scale


def wall_to_canvas(point, bounds, transform):
    min_x, max_x, min_y, max_y = bounds
    origin_x, origin_y, scale = transform
    width_mm = max_x - min_x
    height_mm = max_y - min_y
    used_width = width_mm * scale
    used_height = height_mm * scale
    offset_x = (CANVAS_WIDTH - used_width) / 2.0
    offset_y = (CANVAS_HEIGHT - used_height) / 2.0

    x = int(round(offset_x + (point[0] - origin_x) * scale))
    y = int(round(offset_y + (point[1] - origin_y) * scale))
    return x, y


def draw_axes(canvas, bounds, transform):
    min_x, max_x, min_y, max_y = bounds
    axis_color = (120, 120, 120)

    top_left = wall_to_canvas((min_x, min_y), bounds, transform)
    bottom_left = wall_to_canvas((min_x, max_y), bounds, transform)
    top_right = wall_to_canvas((max_x, min_y), bounds, transform)

    cv2.line(canvas, top_left, bottom_left, axis_color, 2)
    cv2.line(canvas, top_left, top_right, axis_color, 2)

    cv2.putText(
        canvas,
        "Y+",
        (bottom_left[0] - 10, bottom_left[1] + 30),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.7,
        axis_color,
        2,
        cv2.LINE_AA,
    )
    cv2.putText(
        canvas,
        "X+",
        (top_right[0] + 10, top_right[1] + 5),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.7,
        axis_color,
        2,
        cv2.LINE_AA,
    )


def draw_header(canvas, payload):
    reference = payload.get("reference_marker", {})
    item_count = payload.get("marker_count", payload.get("target_count"))
    source = payload.get("source_detection", payload.get("source_wall_coords"))
    reference_id = reference.get("id")
    if reference_id is None and reference.get("ids"):
        reference_id = ",".join(str(marker_id) for marker_id in reference["ids"])
    lines = [
        "Wall Coordinate Preview",
        f"Source: {source}",
        f"Reference ID: {reference_id}, size: {reference.get('marker_size_mm')} mm",
        f"Origin: {reference.get('origin_mode')}, items: {item_count}",
    ]

    y = 30
    for line in lines:
        cv2.putText(
            canvas,
            line,
            (20, y),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.7,
            (40, 40, 40),
            2 if y == 30 else 1,
            cv2.LINE_AA,
        )
        y += 28


def draw_markers(canvas, markers, bounds, transform):
    for marker in markers:
        wall = normalize_wall_geometry(marker["wall_mm"], marker.get("id"))
        corners = wall["corners"]
        center = wall["center"]

        polygon = np.array(
            [wall_to_canvas(point, bounds, transform) for point in corners],
            dtype=np.int32,
        )
        center_canvas = wall_to_canvas(center, bounds, transform)

        if len({tuple(point) for point in polygon.tolist()}) > 1:
            cv2.polylines(canvas, [polygon], True, (0, 120, 255), 2)

            for point in polygon:
                cv2.circle(canvas, tuple(point), 4, (0, 0, 255), -1)

        cv2.circle(canvas, center_canvas, 6, (0, 180, 0), -1)
        cv2.putText(
            canvas,
            f"ID {marker['id']}",
            (center_canvas[0] + 8, center_canvas[1] - 8),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (20, 20, 20),
            2,
            cv2.LINE_AA,
        )
        cv2.putText(
            canvas,
            f"({center[0]:.1f}, {center[1]:.1f}) mm",
            (center_canvas[0] + 8, center_canvas[1] + 18),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.45,
            (50, 50, 50),
            1,
            cv2.LINE_AA,
        )


def render_wall_preview(payload):
    current_object_name = "payload"
    current_object = payload
    current_stage = "extract_marker_like_data"

    try:
        markers, _ = extract_marker_like_data(payload)
        current_object_name = "markers"
        current_object = markers

        current_stage = "collect_wall_points"
        points = collect_wall_points(markers)
        current_object_name = "points"
        current_object = points

        current_stage = "compute_bounds"
        bounds = compute_bounds(points)
        current_object_name = "bounds"
        current_object = bounds

        current_stage = "build_transform"
        transform = build_transform(bounds)
        current_object_name = "transform"
        current_object = transform

        current_stage = "draw_preview"
        canvas = create_canvas()
        draw_header(canvas, payload)
        draw_axes(canvas, bounds, transform)
        draw_markers(canvas, markers, bounds, transform)
        return canvas
    except Exception:
        debug_wall_log_exception(current_stage, current_object_name, current_object)
        raise


def build_output_path(input_path, output_dir):
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    return output_dir / f"{input_path.stem}_preview_{timestamp}.png"


def save_preview(image, input_path, output_dir):
    output_path = build_output_path(input_path, output_dir)
    success = cv2.imwrite(str(output_path), image)
    if not success:
        raise RuntimeError(f"保存预览图失败: {output_path}")
    print(f"[INFO] 已保存墙面预览图: {output_path}")


def show_preview(image, input_path, output_dir):
    print("[INFO] 按 'q' 退出窗口，按 's' 保存预览图。")
    while True:
        cv2.imshow(WINDOW_NAME, image)
        key = cv2.waitKey(0) & 0xFF

        if key == ord("q"):
            print("[INFO] Quit.")
            break
        if key == ord("s"):
            save_preview(image, input_path, output_dir)

    cv2.destroyAllWindows()


def main():
    args = parse_args()

    try:
        input_path = validate_input_path(args.input)
        payload = load_wall_json(input_path)
        output_dir = ensure_output_dir()

        preview = render_wall_preview(payload)
        show_preview(preview, input_path, output_dir)

    except Exception as exc:
        print(f"[ERROR] {exc}")
        sys.exit(1)


if __name__ == "__main__":
    main()
